services:
  mysql:
    image: mysql:8.0
    container_name: mysql-ai
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Bum_123321
      MYSQL_DATABASE: bigbikeblitz
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  model-downloader:
    image: ubuntu:22.04
    volumes:
      - .:/workspace
    working_dir: /workspace
    entrypoint: ["/bin/bash", "-c", "apt-get update && apt-get install -y curl unzip && bash ai_agent/download_blobs.sh"]

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ./ai_agent/models:/root/.ollama/models

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bigbikeblitz?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Bum_123321
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: lhlam.lehoang@gmail.com
      SPRING_MAIL_PASSWORD: ykefobwrfcvdazxp
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: 'true'
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: 'true'
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED: 'true'
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT: 5000
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT: 5000
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT: 5000
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - ollama
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  ai_agent:
    build:
      context: ./ai_agent
      dockerfile: Dockerfile.ai_agent
    container_name: ai_agent
    restart: always
    environment:
      # AI Model Configuration - Using default values for demo
      ANTHROPIC_API_KEY: sk-demo-key-for-testing
      OLLAMA_BASE_URL: http://ollama:11434
      OLLAMA_MODEL: llama3.2:1b
      
      # SSL Certificate Configuration (for enterprise environments)
      SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
      SSL_CERT_DIR: /etc/ssl/certs
      
      # Database Configuration
      DATABASE_URL: sqlite:///ai_agent.db
      
      # Knowledge Base Configuration
      CHROMA_PERSIST_DIRECTORY: ./knowledge_base
      EMBEDDING_MODEL: text-embedding-ada-002
      
      # Web Scraping Configuration
      SCRAPING_DELAY: 1
      MAX_RETRIES: 3
      
      # Logging Configuration
      LOG_LEVEL: INFO
      LOG_FILE: ai_agent.log
      
      # Demo mode - will work without real API keys
      DEMO_MODE: true
    ports:
      - "8000:8000"
    volumes:
      - ai_agent_data:/app/knowledge_base
      - ai_agent_logs:/app/logs
      - ai_agent_db:/app
    depends_on:
      - mysql
      - ollama

volumes:
  mysql_data:
  ai_agent_data:
  ai_agent_logs:
  ai_agent_db: 